[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "convex-mpc-go2"
version = "0.0.0"
dependencies = ["numpy"]

[tool.setuptools]
package-dir = {"" = "src/python"}

[tool.setuptools.packages.find]
where = ["src/python"]
